# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

config_file:
  template: "config.php.dist"
  target: "config.php"


command:
  build:
    - "echo \"www-data   ALL = (ALL) NOPASSWD: /usr/bin/docker\" | sudo tee --append /etc/sudoers"
    - "sudo apt-get -y install docker.io certbot"
    - "composer update"
    - "sudo chmod 777 /srv"

  run:
    - "curl http://localhost/hooks/container-start | python -m json.tool"

  update:
    - "curl http://localhost/api/v1/update | python -m json.tool"
